

def counting_letters(s):
    """
    PROBLEM
    Given: A DNA string s of length at most 1000 bp.
    Return: Four integers (separated by spaces) representing the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s. Note: You must provide your answer in the format shown in the sample output below.

    """

    A_count = 0
    G_count = 0
    C_count = 0
    T_count = 0

    for letter in s:
        if letter == 'A':
            A_count += 1
        elif letter == 'G':
            G_count += 1
        elif letter == 'C':
            C_count += 1
        elif letter == 'T':
            T_count += 1
        else:
            print(f"{letter} does not belong anywhere!")

    print(f"{A_count} {C_count} {G_count} {T_count}")
 

s = "AAGGCATTGTAGAAAAACATCACCTAGGTCTCTGAGTACAGACGCTCGGGGGCGAGTGGCGGAAACCTCGAGAACTTGTGGCACCTTTAAATCCTATACAACGGTCGATATTTCTACGAAAGACCTAAGCAAATACGAACACCACAGCCGGATCCCATAACCCTTAGGGTAATGCCTTTTCCCGTTCATGAAGTTACGAACGGATCAGCAGGCTGTCGCTCTCAACGGAAAGTCGCTAAAGTGGTAATGTTCTATTCGGAGCTCACTAACAGATCCTTAGTAGTGTGGGAGAAATATAGTTCTCACCCATACAGACGGTGTCGATGTGTACGGGGGCCTAAGCGTCAGATATCGGCCTCGCGCCTCAAATCGTTAGACATGAGTTCTCGTGTGCGTGTGCAAACGTAATTTTATGCCGCTGACGCCGCCATTCGCGAAAAGTACGTCGCAACAGGGAGGCCAACAGAGTGAGACAGGCTCCACGGCCGACTATTGGGGCTAGGCAACATGTCTTCAATAAGCGTGGTCGGGAAGTGCGAATCCTCCATGCTTTCATCGTATCTTGGCTCCGCTGGCGGCTAGACTCTGTCCATGTCTTTCCCAACCCGACCGTACGACTATGACAATTAAGGCGGTCTAGGTCATGGTGCTGTATAGCAGAAAGATACCAAACGCCCGCTACGGCACGTCTCTTGCGAAGTTTCGACTCCGGTATTTAGGAGGAGAATATTCTCCTTCCGTCCTCACAGCGGCAGTCCATTATTTCCAATTAAATCCGCCCAACGCCTTGGACGCATGGTTACGGGAGGAAACCCGCAGCTAATATGCCACAAAGTATTTCGATGTATCCTTCACTGAGTAAACCTGTCGAACTCTCCGTAACAAGATACGTTCGCGAATCTCACGAATCCTTGGGTTACACAACAAAAGTGACCCGCGGGAACACCCTACGTAGCAGCTGAT"
print(counting_letters(s))